
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    ##自己是注册中心，是否将自己注册到注册中心上去，集群时需要为true的
    register-with-eureka: true
    ##自己是注册中心不需要去检索服务信息
    fetch-registry: true
spring:
  application:
    name: springcloud-member
  security:
    user:
      name: admin
      password: admin
